# datasource

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=petshop
quarkus.datasource.password=petshop
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/petshop


# hibernate
quarkus.hibernate-orm.schema-management.strategy=none

# liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.sql

# log (útil pra ver o SQL durante dev)
quarkus.hibernate-orm.log.sql=true


